# Generated by Django 6.0.3 on 2026-04-10 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_boya', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('turbidez', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperatura', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('conductividad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('boya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boya')),
            ],
        ),
    ]
